// src/components/react/Counter.tsx
import {useState} from "react";

const Counter = () => {
	const [count, setCount] = useState(0);
	console.log('render react');

	function incrementCount() {
		setCount((count) => count + 1);
	}

	return (
		<>
			<p>react</p>
			<p>Counter: {count}</p>
			<button onClick={incrementCount}>+1</button>
		</>
	);
}

export default Counter;

// src/components/solid/Counter.tsx
import {createSignal} from "solid-js";

const Counter = () => {
	const [count, setCount] = createSignal(0);
	console.log('render solid');

	function incrementCount() {
		setCount(count() + 1);
	}

	return (
		<>
			<p>Solid</p>
			<p>Counter: {count()}</p>
			<button onClick={incrementCount}>+1</button>
		</>
	);
}
export default Counter;
