// src/components/qwik/Counter.tsx
import { component$, useSignal, $ } from "@builder.io/qwik";

export default component$(() => {
	const count = useSignal(0);

	const incrementCount = $(() => count.value++);
	return (
		<>
			<p>Qwik</p>
			<p>Counter: {count.value}</p>
			<button onClick$={incrementCount}>+1</button>
		</>
	);
});

// src/components/react/Counter.tsx
import {useState} from "react";

const Counter = () => {
	const [count, setCount] = useState(0);
	console.log('render react');

	function incrementCount() {
		setCount((count) => count + 1);
	}

	return (
		<>
			<p>react</p>
			<p>Counter: {count}</p>
			<button onClick={incrementCount}>+1</button>
		</>
	);
}

export default Counter;
